from core.db import get_engine_controladoria
import pandas as pd

query = """
SELECT 'USU_T650ORC' TABELA, 'USU_DATALT' COLUNA, COUNT(*) NULOS FROM SAPIENS.USU_T650ORC WHERE USU_DATALT IS NULL
UNION ALL SELECT 'USU_T650CUS', 'USU_DATALT', COUNT(*) FROM SAPIENS.USU_T650CUS WHERE USU_DATALT IS NULL
UNION ALL SELECT 'E044CCU', 'DATALT', COUNT(*) FROM SAPIENS.E044CCU WHERE DATALT IS NULL
UNION ALL SELECT 'E043PCM', 'DATALT', COUNT(*) FROM SAPIENS.E043PCM WHERE DATALT IS NULL
UNION ALL SELECT 'R910USU', 'DATALT', COUNT(*) FROM SAPIENS.R910USU WHERE DATALT IS NULL
ORDER BY 3 DESC
"""

engine = get_engine_controladoria()
df = pd.read_sql(query, engine)
print(df.to_string(index=False))
